### PR TITLE
gradle 7.4.2

### PR DESCRIPTION
**Pull request by sullis**
https://docs.gradle.org/7.4.2/release-notes.html#upgrade-instructions

### CODE REVIEW

**Comment by sullis** [comment]
@jmini

**Comment by sullis** [comment]
can you merge this? @jmini

**Comment by jmini** [comment]
@sullis I really like your PR but a commit to update the wrapper has to update the `gradleVersion` in the wrapper section in the root `build.gradle`:

https://github.com/OpenAPITools/empoa/blob/f1a09f8b4b1ed393ccb95cdc7f0ad4fdf82a8e70/build.gradle#L20-L22

See commit 3a30d58657c65c2303ac080b5479fe3caf9474f9

**Comment by jmini** [comment]
Closing this PR since the current gradle version used is `7.3.3`

**Pull request closed without merging**
